### PR TITLE
Bugfix/securitylog perf

### PR DESCRIPTION
**Pull request by wokhan**

### CODE REVIEW

**Comment by harrwiss** [comment]
Hi @wokhan, could you please resolve the merge conflicts with master - looks like the changes where made based on Common.Tests, before the migration to xunit was done.

**Comment by wokhan** [comment]
I'm on it, I'm ill and had to deal with baby girl so... a bit harder to get going.

**Comment by harrwiss** [comment]
Let me know if I can help out!

**Comment by wokhan** [comment]
Thank you! I merged stuff and modified some others (a bad habit I cannot let go... I'm trying).
I had to "tweak" your tests, but I still think that external calls aren't really a good thing since for instance your tests didn't work for me and won't for other either, especially tests relying on current locale (see my comment in your tests) :-)
I'll stop for today, but i think I can improve some stuff again on the connections and security log pages.
Not even mentioning I managed to speed up initial display of the connections page, but probably broke something afterward since it's still a bit slow (we're talking of 100s of ms here, nothing really bad).
Good evening!

**Comment by harrwiss** [comment]
Thx, and also good evening

**Comment by harrwiss** [comment]
>tests relying on current locale (see my comment in your tests) :-)

ok, thats bad 😒

**Comment by wokhan** [comment]
Don't worry, that's the main issue when using English, you don't know if it's an internal name or display name. Switching to something less international would help 😉

**Pull request merged**
