### PR TITLE
Feature branch1 pull request

### PR DESCRIPTION
**Pull request by harrwiss**
Hi Jerome, here is the pull request I promised, containing several fixes and enhancements.

For a description of major changes see:
https://github.com/harrwiss/WFN/wiki/WFN-Modifications-based-on-2.0-Beta-3

Would be nice if you could review and merge it into your master. Hope you'll not discover major issues given the amount of changes done.

Cheers, Harry

### CODE REVIEW

**Comment by AtlasHackert** [comment]
Can you please split this into multiple pull requests (one per feature), and provide a description for each?)

Also there's a conflict in Common/Helpers/FirewallHelper.cs...

**Comment by harrwiss** [comment]
Don't know why it's reporting a conflict here. For me the two code parts between master and feature-branch look the same to me. 
Also as far as I can see I was the only one having commited since the last pull request merge in June  i.e. there should not be conflicts anyway.

**Comment by wokhan** [comment]
Thank you both.

**Comment by harrwiss** [comment]
I'm taking it back now

**Pull request closed without merging**
