### PR TITLE
Feature/u4 improvements various

### PR DESCRIPTION
**Pull request by harrwiss**
Hi @AtlasHackert  and @wokhan 

These are now the changes for Update 4 (includes u3 with the namespace correction and indiv. test projects). Let me know what you think about the Notifier Tray Icon ;)

Cheers.

**Notifier**
* Implemented a tray notiy icon for notifier which is shown when minimizing
* Keep notifier minimized (silent) when the tray icon is shown
* Animated the tray icon when blocking events triggered (may be improved)
* Added TargetInfoUrl (https://bgpview.io/ip/{0}) and TargetPortUrl (only in app.config) for customization. The previously used TargetInfoUrl displayed a captcha.

**Security Log**
* 	Added tcp only filter checkbox and remote host name column
* 	Added DnsResolver to resolve remote ip's to hostname using dns asynchronous
* 	Improved filter lookup to include wfp state which includes filters from other filter providers besides windows firewall (e.g third party firewall)

**Connections and Map**
*	Added DNS host name resolution for ip addresses in Connections and Map (on the UI)

**Options/Settings**
* 	Added Enable DNS host name resolver setting for Security Log
* 	Added Enable successful connection events setting for Security Log (auditpol /success:enable)

**Settings**
* Had to change CustomSettingsProvider#SectionName to be consistent with the namespace used in the Settings class. Mainly because the Settings.Designer in VS inserted entries in the wrong section in *app.config*.
* Improved parsing in the CustomSettingsProvider on missing or corrupted settings which lead to illegal reference exception. E.g: Loghelper failed to read the FirstRun setting when trying to log an error and then WFN crashed.

***app.config*** 
* Settings are stored under a different section
* Old: *Wokhan.WindowsFirewallNotifier.Configuration*
* New: *Wokhan.WindowsFirewallNotifier.Common.Settings*
* Consequence: User settings in Options are lost/set to defaults from app.config.

***LogHelper***
* Improved null checks, most importantly on Settings.Default.FirstRun which lead to app crash on startup. To avoid this a default setting is used for missing ones.

**Test Projects**
* Created new test projects for Console.Tests and Common.Tests
* Added additional tests for NetshHelper and DnsResolver

**Various**
*    Removed old ip database (IPDatabase.gz)
*    Cleanup and fix some warnings

### CODE REVIEW

**Comment by AtlasHackert** [comment]
Why did you change the type of various settings to Strings, when they obviously are Booleans and Ints?

(And can you PLEASE learn to submit one improvement per pull request? These bulk PRs are incredibly messy.)

**Comment by harrwiss** [comment]
> Why did you change the type of various settings to Strings

I didn't 🚫 but the Settings Designer in VS serializes them as strings. When loaded they are de-serialized to the appropriate type though. Since that's VS generated code, there's not much to do about that I think.

> PLEASE learn to submit one improvement per pull request

Hmm, I'm not getting into a messy discussion now 😈 - point taken. The settings inconsistency and null reference exceptions I had to address because they caused really nasty error messages and crashes.

**Comment by danielmmmm** [comment]
Looking forward to seeing this in the next release :-)
(No, I do not expect this to happen any time soon ;-) )

**Comment by harrwiss** [comment]
Hi @danielmmmm 
If you would like to give it a try you can find the binary here: https://github.com/harrwiss/WFN/releases

**Pull request closed without merging**
